# Generated by Django 4.0.5 on 2023-05-10 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizz', '0002_checktest_checkquestion'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='pass_percentage',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
