# Generated by Django 4.0.5 on 2023-05-10 03:11

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('quizz', '0003_test_pass_percentage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='end_date',
            field=models.DateTimeField(verbose_name=datetime.datetime(2023, 5, 17, 3, 11, 48, 613459, tzinfo=utc)),
        ),
    ]
